### ISSUE TITLE
bool type and lower level access to PostgreSQL

### ISSUE THREAD

**Issue by masaoliou** [artyom-beilis/cppdb#1]
I made some changes to my local version of CppDB so

1. it supports `bool` type. For example, `bool b=cppdb_result.get<bool>(0);`
2. persistant PostgreSQL connections can listen to `NOTIFY`.

Hopefully these changes will be patched on CppDB main branch.
However, patching my work to main branch will break all other underlying drivers because I know only PostgreSQL.

Folks, any idea?

**Comment by dreaming-augustin** [comment]
I use MySQL.
If you provide some testing guidelines, I can try if it works.

For Artyom's sake, it'd be better if you submitted one pull request for each feature or bug fix.
I can review each individually, and test on MySQL if required.

**Comment by masaoliou** [comment]
@dreaming-augustin 
I have created the pull request just now.
